baseURL = 'https://satyasasank.github.io/CodeBlue'
languageCode = 'en-us'
title = 'CodeBlue'
theme = 'bilberry-hugo-theme'
paginate = 2
canonifyurls = true

# Enable / Disable open link with a new tab.
[blackfriday]
  hrefTargetBlank = false


[params]
  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  
  # Description and meta data for the search engines
  author = "Satya Sasank"
  description = "Satya Sasank's Blog"
  keywords = "Computational Fluid Dynamics, linux, OpenFOAM, ANSYS, ANSA, Converge, python programming, Matlab/Octave"

  # How many articles should be displayed at once?
  # paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Media configuration
    # let hugo automatically resize and crop your images to the correct sizes
    # NB: When enabled the image files get renamed by adding additional information,
    #     even if the image has the correct sizes.
    resizeImages = true
    
  # Header configuration
    # your subtitle if you want to use any
    subtitle = "Welcome to my blog!"

    # if you want to use gravatar for the header image
    # gravatarEMail = ""

    # set an path to the image file you want to use | overwrites gravatar
    customImage = ""

    # define the icon you want to use for the overlay for the customImage or gravatar.
    # overlayIcon = "fa-home"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = false

    # always display the top navigation when scrolling
    # works only with permanentTopNav = true
    stickyNav = false

    # show a language chooser in the header
    showHeaderLanguageChooser = false

  # Content configuration
    # Enable an optional pinned page to display at the top of the index
    # pinnedPost = "/content/github/"
    # Set to true to pin only to the first page, false to all pages
    # pinOnlyToFirstPage = true

    # enable automatical localization of the article's PublishedDate with momentjs
    enableMomentJs = true

    # customize the date format | only works if momentjs is disabled | only works with English month names
    # you can customize it with the options you find here:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateFormat = "2006-01-02"

    # display the estimated reading time for an article
    showReadingTime = false

  # Footer configuration
    showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = 7

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 7

    # show a language chooser in the footer
    showFooterLanguageChooser = false

    # social media profile urls for the footer links
    showSocialMedia = true

    # define your links with FontAwesome 5 (only free icons are supported)
    # all icons https://fontawesome.com/icons?d=gallery&m=free
    # brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
    
    socialMediaLinks = [
      { link = "https://www.linkedin.com/in/satya-s-b52717178/", icon = "fab fa-linkedin" },
      { link = "https://github.com/SatyaSasank", icon = "fab fa-github" },           
      { link = "mailto:kssasank43@gmail.com", icon = "fas fa-envelope" },   
    ]

    # credits line configuration
    copyrightBy = "Satya Sasank"
    copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
    copyrightYearOverride = "2021"
    copyrightUrl = "https://github.com/satyasasank"
    creditsText = "Powered by Bilberry Hugo Theme"
    creditsUrl = "https://github.com/Lednerb/bilberry-hugo-theme"


# customize your available languages for your multi-langual site
# or delete the [Languages] blog to use the theme with only one supported language
[Languages]
  [Languages.en]
    weight = 1

# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]